spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/second-kill?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&usessl=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1 FROM DUAL
      initialSize: 5
      min-idle: 5
      max-active: 20
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
